image:
  file: .gitpod.Dockerfile

tasks:
  - name: Postgres
    command: |
      .gitpod/init-postgres.sh
      .gitpod/periodic-backup-postgres.sh
  - name: Main
    command: |
      echo "Welcome to Gitpod."

ports:
  - name: PostgestSQL
    port: 5432
    visibility: private
  - port: 43685
    visibility: private
