image:
  file: .gitpod.Dockerfile
workspaceLocation: postgres-test/ws.code-workspace

tasks:
  - name: Postgres
    command: |
      .gitpod/init-postgres.sh
      .gitpod/periodic_backup.sh

ports:
  - name: PostgestSQL
    port: 5432
    visibility: private
  - port: 43685
    visibility: private
